### ISSUE TITLE
[FR] Enable files dependencies

### ISSUE THREAD

**Issue by JohnPreston** [compose-x/ecs-files-composer#10]
I want to be able to define that one file depends on the presence of another before acquiring.

```yaml
files:
  /path/to/A: {}
  /path/to/B:
    depends_on:
      - /path/to/A
```
